author: Ryan Will
defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
  -
    scope:
      path: "_drafts"
    values:
      layout: "post"
description: 'Cultivating ideas and software with varying degrees of success'
highlighter: rouge
include:
  - _redirects
kramdown:
  input: GFM
markdown: kramdown
metadata:
  title: 'Software Developer'
  description: 'Cultivating ideas and software with varying degrees of success'
  keywords:
     'nashville,tennessee,software,development,developer,website,custom,blog,web,dickson,elixir,phoenix,javascript,ruby,rails'
permalink: "/writing/:title"
sass:
  sass_dir: _sass
  style: compressed
tag_page_layout: tag_page
tag_page_dir: tag
url: 'https://www.ryanwill.dev'
